build:
  no_build: true

clusters:
  basic-cluster-props: &default-cluster-spec
    spark_version: "12.2.x-cpu-ml-scala2.12"
    node_type_id: 'Standard_D4a_v4'
    driver_node_type_id: 'Standard_D4a_v4'
    num_workers: 1

  staging-cluster-config: &staging-cluster-config
    new_cluster:
      <<: *default-cluster-spec
      spark_env_vars:
        ENV: "test"

  prod-cluster-config: &prod-cluster-config
    new_cluster:
      <<: *default-cluster-spec
      spark_env_vars:
        ENV: "test"

git:
  odap-git-source: &odap-git-source
    git_url: "https://github.com/DataSentics/e2e-mlops-azure.git"
    git_provider: "github"
    git_branch: "ll-simplify"

environments:
  prod:
    workflows:
      - name: "inference_pipeline"
        git_source: *odap-git-source
        job_clusters:
          - job_cluster_key: "default"
            <<: *prod-cluster-config
        tasks:
          - &feature_table_update
            task_key: "feature_table_update"
            deployment_config:
              no_package: true
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "telco_churn/features/customer_features"
          - &run_inference
            task_key: "run_inference"
            deployment_config:
              no_package: true
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "telco_churn/models/churn_prediction/inference"
            depends_on:
              - task_key: "feature_table_update"

      - name: "train_churn_model"
        git_source: *odap-git-source
        job_clusters:
          - job_cluster_key: "default"
            <<: *prod-cluster-config
        tasks:
          - task_key: "train_model"
            deployment_config:
              no_package: true
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "telco_churn/models/churn_prediction/train"
          - task_key: "replace_production_model"
            deployment_config:
              no_package: true
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "telco_churn/deploy/replace_model"
            depends_on:
              - task_key: "train_model"
  staging:
    workflows:
      - name: "test_inference_pipeline"
        git_source: *odap-git-source
        job_clusters:
          - job_cluster_key: "default"
            <<: *staging-cluster-config
        tasks:
          - <<: *feature_table_update
          - <<: *run_inference
