build:
  no_build: true

clusters:
  basic-cluster-props: &basic-cluster-props
    spark_version: "12.2.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 1
      instance_pool_id: "0405-095028-super222-pool-6j0p3smq"

git:
  odap-git-source: &odap-git-source
    git_url: "https://github.com/DataSentics/e2e-mlops-azure.git"
    git_provider: "github"
    git_branch: "ll-simplify"

environments:
  dev:
    workflows:
      - name: "inference_pipeline"
        git_source: *odap-git-source
        job_clusters:
          - job_cluster_key: "default"
            <<: *basic-static-cluster
        tasks:
          - task_key: "feature_table_update"
            deployment_config:
              no_package: true
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "telco_churn/features/customer_features"
          - task_key: "run_inference"
            deployment_config:
              no_package: true
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "telco_churn/models/churn_inference"
            depends_on:
              - task_key: "feature_table_update"

      - name: "train_churn_model"
        git_source: *odap-git-source
        job_clusters:
          - job_cluster_key: "default"
            <<: *basic-static-cluster
        tasks:
          - task_key: "train_model"
            deployment_config:
              no_package: true
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "telco_churn/models/train_churn"
          - task_key: "replace_production_model"
            deployment_config:
              no_package: true
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "deploy/replace_model"
            depends_on:
              - task_key: "train_model"
