name: Release pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  pipeline:

    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Train model in production
        run: |
          dbx deploy train_churn_model --deployment-file deployment.yml --environment=prod
          dbx launch train_churn_model --environment=dev --trace --existing-runs wait
      - name: Train model in production
        run: |
          dbx deploy inference_pipeline --deployment-file deployment.yml --environment=prod
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release for version ${{ github.ref }}.
          draft: false
          prerelease: false
